In [725]:
import pandas as pd
events = pd.read_excel("new2022.xlsx",index_col=False,keep_default_na=True, sheet_name='Export')

In [726]:
events

,N°,DATE,PAYS,Type,Nom du client,departement,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change,Banque
0,1,2022-01-05,Belgique,CLIENTS ETRANGERS,BAQUILA,ELECTRICITE\n,5960.272394,3.3059,19704.064510,3221.768861,2738.503532,3231.517510,ATTIJARI TND
1,2,2022-01-10,France,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE\n,11809.074839,3.3059,39039.620510,9437.444929,2371.629911,5207.368421,BIAT TND
2,3,2022-02-15,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,30354.000000,3.3059,100347.288600,16407.567568,13946.432430,3209.143969,ATTIJARI TND
3,4,2022-02-26,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,FLUIDE,9767.392500,3.3059,32290.022870,7805.795972,1961.596528,3317.894737,BIAT TND
4,5,2022-02-26,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,8600.300000,3.3059,28431.731770,6873.091984,1727.208016,3521.052632,BIAT TND
5,6,2022-03-07,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,GENI CIVIL,29610.236000,3.3059,97888.479190,16005.532973,13604.703030,2109.922179,ATTIJARI TND
6,7,2022-03-28,Belgique,CLIENTS ETRANGERS,BAQUILA,GENI CIVIL,10118.000000,3.3059,33449.096200,5469.189189,4648.810811,3993.190661,ATTIJARI TND
7,8,2022-03-28,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,34060.970500,3.3059,112602.162400,34060.970500,0.000000,4845.263158,BIAT TND
8,9,2022-04-02,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,FLUIDE,14802.634000,3.3059,48936.027740,8001.423784,6801.210216,2171.206226,ATTIJARI TND
9,10,2022-04-02,france,CLIENTS ETRANGERS,DELTA BETA,FLUIDE,18500.750000,3.3059,61161.629430,18500.750000,0.000000,4774.736842,ZITOUNA €
10,11,2022-04-10,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,FLUIDE,9042.050000,3.3059,29892.113100,9042.050000,0.000000,1449.119470,ZITOUNA €
11,12,2022-04-25,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,37657.293000,3.3059,124491.244900,20355.293514,17301.999490,3009.727626,ATTIJARI TND
12,13,2022-04-30,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE\n,3439.860000,3.3059,11371.833170,1859.383784,1580.476216,3961.089494,ATTIJARI TND
13,14,2022-04-30,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE\n,8687.972000,3.3059,28721.566630,6943.156717,1744.815283,2767.509728,BIAT €
14,15,2022-05-21,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,ELECTRICITE\n,12288.964103,3.3059,40626.086430,12288.964103,0.000000,1208.606730,ZITOUNA €
15,16,2022-05-29,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,FLUIDE,1071.794872,3.3059,3543.246667,856.545091,215.249781,3998.054475,BIAT €
16,17,2022-05-31,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE\n,3333.333333,3.3059,11019.666670,2663.896215,669.437119,3760.700389,BIAT €
17,18,2022-06-25,Tunisie,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,9693.061538,3.3059,32044.292140,5701.800905,3991.260633,1910.202937,ZITOUNA TND
18,19,2022-06-26,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE\n,1333.333333,3.3059,4407.866667,1065.558486,267.774848,3146.887160,BIAT €
19,20,2022-06-27,france,CLIENTS ETRANGERS,DELTA BETA,FLUIDE,2322.222222,3.3059,7677.034444,2322.222222,0.000000,2215.376137,ZITOUNA €
20,21,2022-07-23,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,FLUIDE,1833.333333,3.3059,6060.816667,1465.142918,368.190415,3888.132296,BIAT €
21,22,2022-07-24,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,FLUIDE,18010.233918,3.3059,59540.032310,18010.233918,0.000000,2447.428629,ZITOUNA €
22,23,2022-08-27,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,1888.175439,3.3059,6242.119182,1508.971021,379.204418,4661.052632,BIAT €
23,24,2022-08-28,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,ELECTRICITE\n,5994.152047,3.3059,19816.067250,3525.971792,2468.180255,2080.012183,ZITOUNA €
24,25,2022-09-25,france,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE\n,13314.602339,3.3059,44016.743870,7832.119023,5482.483316,1530.096120,ZITOUNA TND
25,26,2022-10-24,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,25697.491178,3.3059,84953.336090,15116.171281,10581.319900,1670.898805,ZITOUNA TND
26,27,2022-11-24,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,27696.248811,3.3059,91561.028940,16291.911065,11404.337750,2141.651126,ZITOUNA TND
27,28,2022-12-03,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,GENI CIVIL,2575.239480,3.3059,8513.484197,2058.051211,517.188269,3693.684211,BIAT TND
28,29,2022-12-24,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,GENI CIVIL,21911.745480,3.3059,72438.039380,12889.262047,9022.483433,2740.515761,ZITOUNA TND

In [727]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   N°               29 non-null     int64
 1   DATE             29 non-null     datetime64[ns]
 2   PAYS             29 non-null     object
 3   Type             29 non-null     object
 4   Nom du client    29 non-null     object
 5   departement      29 non-null     object
 6   CA €             29 non-null     float64
 7   tx conv          29 non-null     float64
 8   CA TND           29 non-null     float64
 9   Recouvrement €   29 non-null     float64
 10  Restant €        29 non-null     float64
 11  Perte de change  29 non-null     float64
 12  Banque           29 non-null     object
dtypes: datetime64[ns](1), float64(6), int64(1), object(5)
memory usage: 3.1+ KB

In [728]:
events['PAYS'] = events['PAYS'].replace("Tunisie", "France")

In [729]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['CA €', 'tx conv', 'CA TND', 'Recouvrement €', 'Restant €', 'Perte de change']
for col in cols_to_convert:
    events[col] = events[col].apply(convert_comma_to_float)

In [730]:
events['Banque'] = events['Banque'].str.replace('TND', '€')

In [731]:
events.head()

,N°,DATE,PAYS,Type,Nom du client,departement,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change,Banque
0,1,2022-01-05,Belgique,CLIENTS ETRANGERS,BAQUILA,ELECTRICITE\n,5960.272394,3.3059,19704.06451,3221.768861,2738.503532,3231.517510,ATTIJARI €
1,2,2022-01-10,France,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE\n,11809.074839,3.3059,39039.62051,9437.444929,2371.629911,5207.368421,BIAT €
2,3,2022-02-15,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,30354.000000,3.3059,100347.28860,16407.567568,13946.432430,3209.143969,ATTIJARI €
3,4,2022-02-26,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,FLUIDE,9767.392500,3.3059,32290.02287,7805.795972,1961.596528,3317.894737,BIAT €
4,5,2022-02-26,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,8600.300000,3.3059,28431.73177,6873.091984,1727.208016,3521.052632,BIAT €

In [732]:
events['departement'] = events['departement'].str.strip()

In [733]:
events.head()

,N°,DATE,PAYS,Type,Nom du client,departement,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change,Banque
0,1,2022-01-05,Belgique,CLIENTS ETRANGERS,BAQUILA,ELECTRICITE,5960.272394,3.3059,19704.06451,3221.768861,2738.503532,3231.517510,ATTIJARI €
1,2,2022-01-10,France,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE,11809.074839,3.3059,39039.62051,9437.444929,2371.629911,5207.368421,BIAT €
2,3,2022-02-15,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,30354.000000,3.3059,100347.28860,16407.567568,13946.432430,3209.143969,ATTIJARI €
3,4,2022-02-26,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,FLUIDE,9767.392500,3.3059,32290.02287,7805.795972,1961.596528,3317.894737,BIAT €
4,5,2022-02-26,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,8600.300000,3.3059,28431.73177,6873.091984,1727.208016,3521.052632,BIAT €

In [734]:
import pandas as pd
events1 = pd.read_excel("new2022.xlsx",index_col=False,keep_default_na=True, sheet_name='Local')

In [735]:
events1['PAYS'] = events1['PAYS'].replace("france", "Tunisie")

In [736]:
events1 = events1.rename(columns={'date': 'Type'})

In [737]:
events1['Type'] = events1['Type'].replace("CLIENTS ETRANGERS", "CLIENTS TUNISIENS")

In [738]:
events1['departement'] = events1['departement'].str.strip()

In [739]:
events1['Banque'] = events1['Banque'].str.replace('€', 'TND')

In [740]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['CA HT', 'tva 19%', 'TTC', 'RECOUVREMENT', 'RESTANT']
for col in cols_to_convert:
    events1[col] = events1[col].apply(convert_comma_to_float)

In [741]:
import pandas as pd
events2 = pd.read_excel("new2022.xlsx",index_col=False,keep_default_na=True, sheet_name='Dépenses')

In [742]:
events2['DEPARTEMENT'] = events2['DEPARTEMENT'].replace("ELEC", "ELECTRICITE")

In [743]:
events2['DEPARTEMENT'] = events2['DEPARTEMENT'].replace("GCIVILE", "GENI CIVIL")

In [744]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['HT', 'TVA', 'TTC']
for col in cols_to_convert:
    events2[col] = events2[col].apply(convert_comma_to_float)

In [745]:
import pandas as pd
events3 = pd.read_excel("new2022.xlsx",index_col=False,keep_default_na=True, sheet_name='Salaires')

In [746]:
events3['DEPARTEMENT'] = events3['DEPARTEMENT'].replace("ELEC", "ELECTRICITE")

In [747]:
events3['DEPARTEMENT'] = events3['DEPARTEMENT'].replace("GCIVILE", "GENI CIVIL")

In [748]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['CNSS', 'FISCAL', 'COUT TOTAL']
for col in cols_to_convert:
    events3[col] = events3[col].apply(convert_comma_to_float)

In [749]:
import pandas as pd
events4 = pd.read_excel("new2023.xlsx",index_col=False,keep_default_na=True, sheet_name='Export')

In [750]:
import pandas as pd

events4['new_date'] = pd.to_datetime(
    events4['DATE'],
    errors='coerce' 
)
events4['new_date'] = events4['new_date'].ffill()

events4['new_date'] = events4['new_date'].apply(
    lambda x: x.strftime("%Y-%m-%d %H:%M:%S") if pd.notnull(x) else pd.NA
)

print(events4)

    N°                 DATE      PAYS               Type       Nom du client  \
0    1  2023-01-13 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
1    2  2023-01-24 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
2    3  2023-01-24 00:00:00    france  CLIENTS ETRANGERS          DELTA BETA
3    4           02/02/2023  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
4    5  2023-02-23 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
5    6  2023-02-23 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
6    7  2023-02-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
7    8  2023-03-08 00:00:00    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
8    9  2023-03-23 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
9    9             29/02/23    france  CLIENTS ETRANGERS          DELTA BETA
10  11  2023-03-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
11  12  2023-03-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
12  13  2023-04-18 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
13  10  2023-04-26 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
14  15  2023-04-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
15  16           23/05/2023   Tunisie  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
16  17  2023-05-24 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
17  18           25/05/2023    france  CLIENTS ETRANGERS          DELTA BETA
18  19  2023-06-20 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
19  20  2023-06-21 00:00:00    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
20  20  2023-07-25 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
21  21  2023-07-26 00:00:00    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
22  22           23/08/2023    france  CLIENTS ETRANGERS          DELTA BETA
23  23  2023-09-21 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
24  24           32/10/2023    france  CLIENTS ETRANGERS          DELTA BETA
25  25  2023-10-31 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
26  26          21/11/20 23    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
27  27  2023-12-08 00:00:00   Tunisie  CLIENTS ETRANGERS          DELTA BETA
28  28             23/13/23  Belgique  CLIENTS ETRANGERS             BAQUILA

      departement  N° FCT      CA €  tx conv         CA TND  Recouvrement €  \
0          FLUIDE   18173   6000.00   3.3702   20221.200000         6000.00
1          FLUIDE   18174  33557.50   3.3702  113095.486500        33557.50
2      GENI CIVIL   18175   1700.00   3.3702    5729.340000         1700.00
3      GENI CIVIL   18176  10004.00   3.3702   33715.480800        10004.00
4      GENI CIVIL   18177  26499.50   3.3702   89308.614900        12000.00
5      GENI CIVIL   18178   2000.00   3.3702    6740.400000         2000.00
6          FLUIDE   18179   2926.00   3.3702    9861.205200         2926.00
7          FLUIDE   18180   4950.00   3.3702   16682.490000         4950.00
8          FLUIDE   18181  17327.00   3.3702   58395.455400        17000.00
9          FLUIDE   18182   4250.00   3.3702   14323.350000         4250.00
10  ELECTRICITE\n   18183  12540.00   3.3702   42262.308000        12540.00
11  ELECTRICITE\n   18184   2508.00   3.3702    8452.461600            0.00
12  ELECTRICITE\n   18185  23963.48   3.3702   80761.720296        15000.00
13         FLUIDE   18186   2090.00   3.3702    7043.718000         2090.00
14  ELECTRICITE\n   18187   6500.00   3.3702   21906.300000         6500.00
15     GENI CIVIL   18188  32551.47   3.3702  109704.964194        32551.47
16  ELECTRICITE\n   18189   2600.00   3.3702    8762.520000         1000.00
17         FLUIDE   18190   3971.00   3.3702   13383.064200         3971.00
18         FLUIDE   18191   3135.00   3.3702   10565.577000         3135.00
19         FLUIDE   18192  30797.50   3.3702  103793.734500        30797.50
20         FLUIDE   18193  20328.78   3.3702   68512.054356        20328.78
21  ELECTRICITE\n   18194   1700.00   3.3702    5729.340000         1700.00
22  ELECTRICITE\n   18195  22767.97   3.3702   76732.612494        22767.97
23     GENI CIVIL   18196  34765.43   3.3702  117166.452186        29000.00
24     GENI CIVIL   18197  26973.10   3.3702   90904.741620        22000.00
25     GENI CIVIL   18198   2508.00   3.3702    8452.461600         2508.00
26     GENI CIVIL   18199  21339.63   3.3702   71918.821026        19000.00
27  ELECTRICITE\n   18200  11500.74   3.3702   38759.793948         9000.00
28  ELECTRICITE\n   18201  35021.35   3.3702  118028.953770            0.00

    Restant €  Perte de change        Banque             new_date
0        0.00             3299  ATTIJARI TND  2023-01-13 00:00:00
1        0.00             3152  ATTIJARI TND  2023-01-24 00:00:00
2        0.00             3345     ZITOUNA €  2023-01-24 00:00:00
3        0.00             2169      BIAT TND  2023-02-02 00:00:00
4    14499.50             4603  ATTIJARI TND  2023-02-23 00:00:00
5        0.00             4105   ZITOUNA TND  2023-02-23 00:00:00
6        0.00             2232        BIAT €  2023-02-28 00:00:00
7        0.00             2398        BIAT €  2023-03-08 00:00:00
8      327.00             3094        BIAT €  2023-03-23 00:00:00
9        0.00             4536  ATTIJARI TND  2023-03-23 00:00:00
10       0.00             4072  ATTIJARI TND  2023-03-28 00:00:00
11    2508.00             2845      BIAT TND  2023-03-28 00:00:00
12    8963.48             2000      BIAT TND  2023-04-18 00:00:00
13       0.00             4110  ATTIJARI TND  2023-04-26 00:00:00
14       0.00             3866  ATTIJARI TND  2023-04-28 00:00:00
15       0.00             3161          BIAT  2023-05-23 00:00:00
16    1600.00             3235          BIAT  2023-05-24 00:00:00
17       0.00             3666          BIAT  2023-05-25 00:00:00
18       0.00             3997     ZITOUNA €  2023-06-20 00:00:00
19       0.00             4050   ZITOUNA TND  2023-06-21 00:00:00
20       0.00             4428     ZITOUNA €  2023-07-25 00:00:00
21       0.00             3442     ZITOUNA €  2023-07-26 00:00:00
22       0.00             2532        BIAT €  2023-08-23 00:00:00
23    5765.43             2765        BIAT €  2023-09-21 00:00:00
24    4973.10             3544   ZITOUNA TND  2023-09-21 00:00:00
25       0.00             3509   ZITOUNA TND  2023-10-31 00:00:00
26    2339.63             4535     ZITOUNA €  2020-11-21 23:00:00
27    2500.74             4947     ZITOUNA €  2023-12-08 00:00:00
28   35021.35             3322        BIAT €  2023-12-08 00:00:00

In [751]:
index_9 = events4[events4['N°'] == 9].index.tolist()
print(f"\nIndex avec N°=9: {index_9}")

# Si on a au moins 2 index avec 9, renommer le deuxième
if len(index_9) >= 2:
    deuxieme_index = index_9[1]
    events4.loc[deuxieme_index, 'N°'] = 10
print(events4)

Index avec N°=9: [8, 9]
    N°                 DATE      PAYS               Type       Nom du client  \
0    1  2023-01-13 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
1    2  2023-01-24 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
2    3  2023-01-24 00:00:00    france  CLIENTS ETRANGERS          DELTA BETA
3    4           02/02/2023  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
4    5  2023-02-23 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
5    6  2023-02-23 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
6    7  2023-02-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
7    8  2023-03-08 00:00:00    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
8    9  2023-03-23 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
9   10             29/02/23    france  CLIENTS ETRANGERS          DELTA BETA
10  11  2023-03-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
11  12  2023-03-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
12  13  2023-04-18 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
13  10  2023-04-26 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
14  15  2023-04-28 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
15  16           23/05/2023   Tunisie  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
16  17  2023-05-24 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
17  18           25/05/2023    france  CLIENTS ETRANGERS          DELTA BETA
18  19  2023-06-20 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
19  20  2023-06-21 00:00:00    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
20  20  2023-07-25 00:00:00  Belgique  CLIENTS ETRANGERS             BAQUILA
21  21  2023-07-26 00:00:00    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
22  22           23/08/2023    france  CLIENTS ETRANGERS          DELTA BETA
23  23  2023-09-21 00:00:00    France  CLIENTS ETRANGERS   TRIPARTIE TRAVAUX
24  24           32/10/2023    france  CLIENTS ETRANGERS          DELTA BETA
25  25  2023-10-31 00:00:00  Belgique  CLIENTS ETRANGERS           MAXIBIMAX
26  26          21/11/20 23    France  CLIENTS ETRANGERS  K.WEST INGENIEURIE
27  27  2023-12-08 00:00:00   Tunisie  CLIENTS ETRANGERS          DELTA BETA
28  28             23/13/23  Belgique  CLIENTS ETRANGERS             BAQUILA

      departement  N° FCT      CA €  tx conv         CA TND  Recouvrement €  \
0          FLUIDE   18173   6000.00   3.3702   20221.200000         6000.00
1          FLUIDE   18174  33557.50   3.3702  113095.486500        33557.50
2      GENI CIVIL   18175   1700.00   3.3702    5729.340000         1700.00
3      GENI CIVIL   18176  10004.00   3.3702   33715.480800        10004.00
4      GENI CIVIL   18177  26499.50   3.3702   89308.614900        12000.00
5      GENI CIVIL   18178   2000.00   3.3702    6740.400000         2000.00
6          FLUIDE   18179   2926.00   3.3702    9861.205200         2926.00
7          FLUIDE   18180   4950.00   3.3702   16682.490000         4950.00
8          FLUIDE   18181  17327.00   3.3702   58395.455400        17000.00
9          FLUIDE   18182   4250.00   3.3702   14323.350000         4250.00
10  ELECTRICITE\n   18183  12540.00   3.3702   42262.308000        12540.00
11  ELECTRICITE\n   18184   2508.00   3.3702    8452.461600            0.00
12  ELECTRICITE\n   18185  23963.48   3.3702   80761.720296        15000.00
13         FLUIDE   18186   2090.00   3.3702    7043.718000         2090.00
14  ELECTRICITE\n   18187   6500.00   3.3702   21906.300000         6500.00
15     GENI CIVIL   18188  32551.47   3.3702  109704.964194        32551.47
16  ELECTRICITE\n   18189   2600.00   3.3702    8762.520000         1000.00
17         FLUIDE   18190   3971.00   3.3702   13383.064200         3971.00
18         FLUIDE   18191   3135.00   3.3702   10565.577000         3135.00
19         FLUIDE   18192  30797.50   3.3702  103793.734500        30797.50
20         FLUIDE   18193  20328.78   3.3702   68512.054356        20328.78
21  ELECTRICITE\n   18194   1700.00   3.3702    5729.340000         1700.00
22  ELECTRICITE\n   18195  22767.97   3.3702   76732.612494        22767.97
23     GENI CIVIL   18196  34765.43   3.3702  117166.452186        29000.00
24     GENI CIVIL   18197  26973.10   3.3702   90904.741620        22000.00
25     GENI CIVIL   18198   2508.00   3.3702    8452.461600         2508.00
26     GENI CIVIL   18199  21339.63   3.3702   71918.821026        19000.00
27  ELECTRICITE\n   18200  11500.74   3.3702   38759.793948         9000.00
28  ELECTRICITE\n   18201  35021.35   3.3702  118028.953770            0.00

    Restant €  Perte de change        Banque             new_date
0        0.00             3299  ATTIJARI TND  2023-01-13 00:00:00
1        0.00             3152  ATTIJARI TND  2023-01-24 00:00:00
2        0.00             3345     ZITOUNA €  2023-01-24 00:00:00
3        0.00             2169      BIAT TND  2023-02-02 00:00:00
4    14499.50             4603  ATTIJARI TND  2023-02-23 00:00:00
5        0.00             4105   ZITOUNA TND  2023-02-23 00:00:00
6        0.00             2232        BIAT €  2023-02-28 00:00:00
7        0.00             2398        BIAT €  2023-03-08 00:00:00
8      327.00             3094        BIAT €  2023-03-23 00:00:00
9        0.00             4536  ATTIJARI TND  2023-03-23 00:00:00
10       0.00             4072  ATTIJARI TND  2023-03-28 00:00:00
11    2508.00             2845      BIAT TND  2023-03-28 00:00:00
12    8963.48             2000      BIAT TND  2023-04-18 00:00:00
13       0.00             4110  ATTIJARI TND  2023-04-26 00:00:00
14       0.00             3866  ATTIJARI TND  2023-04-28 00:00:00
15       0.00             3161          BIAT  2023-05-23 00:00:00
16    1600.00             3235          BIAT  2023-05-24 00:00:00
17       0.00             3666          BIAT  2023-05-25 00:00:00
18       0.00             3997     ZITOUNA €  2023-06-20 00:00:00
19       0.00             4050   ZITOUNA TND  2023-06-21 00:00:00
20       0.00             4428     ZITOUNA €  2023-07-25 00:00:00
21       0.00             3442     ZITOUNA €  2023-07-26 00:00:00
22       0.00             2532        BIAT €  2023-08-23 00:00:00
23    5765.43             2765        BIAT €  2023-09-21 00:00:00
24    4973.10             3544   ZITOUNA TND  2023-09-21 00:00:00
25       0.00             3509   ZITOUNA TND  2023-10-31 00:00:00
26    2339.63             4535     ZITOUNA €  2020-11-21 23:00:00
27    2500.74             4947     ZITOUNA €  2023-12-08 00:00:00
28   35021.35             3322        BIAT €  2023-12-08 00:00:00

In [752]:
events4['PAYS'] = events4['PAYS'].replace("Tunisie", "france")

In [753]:
events4['departement'] = events4['departement'].str.strip()

In [754]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['CA €', 'tx conv', 'CA TND', 'Recouvrement €', 'Restant €']
for col in cols_to_convert:
    events4[col] = events4[col].apply(convert_comma_to_float)

In [755]:
events4['Banque'] = events4['Banque'].str.replace('TND', '€')

In [756]:
def corriger_biat(valeur):
    if pd.isna(valeur):
        return valeur
    
    valeur_str = str(valeur).strip()
    
   
    if valeur_str.upper() == 'BIAT':
        return 'BIAT €'
    
   
    return valeur_str


events4['Banque'] = events4['Banque'].apply(corriger_biat)

In [757]:
events4

,N°,DATE,PAYS,Type,Nom du client,departement,N° FCT,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change,Banque,new_date
0,1,2023-01-13 00:00:00,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,18173,6000.00,3.3702,20221.200000,6000.00,0.00,3299,ATTIJARI €,2023-01-13 00:00:00
1,2,2023-01-24 00:00:00,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,FLUIDE,18174,33557.50,3.3702,113095.486500,33557.50,0.00,3152,ATTIJARI €,2023-01-24 00:00:00
2,3,2023-01-24 00:00:00,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,18175,1700.00,3.3702,5729.340000,1700.00,0.00,3345,ZITOUNA €,2023-01-24 00:00:00
3,4,02/02/2023,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,GENI CIVIL,18176,10004.00,3.3702,33715.480800,10004.00,0.00,2169,BIAT €,2023-02-02 00:00:00
4,5,2023-02-23 00:00:00,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,18177,26499.50,3.3702,89308.614900,12000.00,14499.50,4603,ATTIJARI €,2023-02-23 00:00:00
5,6,2023-02-23 00:00:00,Belgique,CLIENTS ETRANGERS,BAQUILA,GENI CIVIL,18178,2000.00,3.3702,6740.400000,2000.00,0.00,4105,ZITOUNA €,2023-02-23 00:00:00
6,7,2023-02-28 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,FLUIDE,18179,2926.00,3.3702,9861.205200,2926.00,0.00,2232,BIAT €,2023-02-28 00:00:00
7,8,2023-03-08 00:00:00,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,FLUIDE,18180,4950.00,3.3702,16682.490000,4950.00,0.00,2398,BIAT €,2023-03-08 00:00:00
8,9,2023-03-23 00:00:00,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,18181,17327.00,3.3702,58395.455400,17000.00,327.00,3094,BIAT €,2023-03-23 00:00:00
9,10,29/02/23,france,CLIENTS ETRANGERS,DELTA BETA,FLUIDE,18182,4250.00,3.3702,14323.350000,4250.00,0.00,4536,ATTIJARI €,2023-03-23 00:00:00
10,11,2023-03-28 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE,18183,12540.00,3.3702,42262.308000,12540.00,0.00,4072,ATTIJARI €,2023-03-28 00:00:00
11,12,2023-03-28 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE,18184,2508.00,3.3702,8452.461600,0.00,2508.00,2845,BIAT €,2023-03-28 00:00:00
12,13,2023-04-18 00:00:00,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,ELECTRICITE,18185,23963.48,3.3702,80761.720296,15000.00,8963.48,2000,BIAT €,2023-04-18 00:00:00
13,10,2023-04-26 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,FLUIDE,18186,2090.00,3.3702,7043.718000,2090.00,0.00,4110,ATTIJARI €,2023-04-26 00:00:00
14,15,2023-04-28 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE,18187,6500.00,3.3702,21906.300000,6500.00,0.00,3866,ATTIJARI €,2023-04-28 00:00:00
15,16,23/05/2023,france,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,18188,32551.47,3.3702,109704.964194,32551.47,0.00,3161,BIAT €,2023-05-23 00:00:00
16,17,2023-05-24 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,ELECTRICITE,18189,2600.00,3.3702,8762.520000,1000.00,1600.00,3235,BIAT €,2023-05-24 00:00:00
17,18,25/05/2023,france,CLIENTS ETRANGERS,DELTA BETA,FLUIDE,18190,3971.00,3.3702,13383.064200,3971.00,0.00,3666,BIAT €,2023-05-25 00:00:00
18,19,2023-06-20 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,FLUIDE,18191,3135.00,3.3702,10565.577000,3135.00,0.00,3997,ZITOUNA €,2023-06-20 00:00:00
19,20,2023-06-21 00:00:00,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,FLUIDE,18192,30797.50,3.3702,103793.734500,30797.50,0.00,4050,ZITOUNA €,2023-06-21 00:00:00
20,20,2023-07-25 00:00:00,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,18193,20328.78,3.3702,68512.054356,20328.78,0.00,4428,ZITOUNA €,2023-07-25 00:00:00
21,21,2023-07-26 00:00:00,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,ELECTRICITE,18194,1700.00,3.3702,5729.340000,1700.00,0.00,3442,ZITOUNA €,2023-07-26 00:00:00
22,22,23/08/2023,france,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE,18195,22767.97,3.3702,76732.612494,22767.97,0.00,2532,BIAT €,2023-08-23 00:00:00
23,23,2023-09-21 00:00:00,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,18196,34765.43,3.3702,117166.452186,29000.00,5765.43,2765,BIAT €,2023-09-21 00:00:00
24,24,32/10/2023,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,18197,26973.10,3.3702,90904.741620,22000.00,4973.10,3544,ZITOUNA €,2023-09-21 00:00:00
25,25,2023-10-31 00:00:00,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,GENI CIVIL,18198,2508.00,3.3702,8452.461600,2508.00,0.00,3509,ZITOUNA €,2023-10-31 00:00:00
26,26,21/11/20 23,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,GENI CIVIL,18199,21339.63,3.3702,71918.821026,19000.00,2339.63,4535,ZITOUNA €,2020-11-21 23:00:00
27,27,2023-12-08 00:00:00,france,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE,18200,11500.74,3.3702,38759.793948,9000.00,2500.74,4947,ZITOUNA €,2023-12-08 00:00:00
28,28,23/13/23,Belgique,CLIENTS ETRANGERS,BAQUILA,ELECTRICITE,18201,35021.35,3.3702,118028.953770,0.00,35021.35,3322,BIAT €,2023-12-08 00:00:00

In [758]:
import pandas as pd
events5 = pd.read_excel("new2023.xlsx",index_col=False,keep_default_na=True, sheet_name='Local')

In [759]:
index_9 = events5[events5['N°'] == 9].index.tolist()
print(f"\nIndex avec N°=9: {index_9}")

# Si on a au moins 2 index avec 9, renommer le deuxième
if len(index_9) >= 2:
    deuxieme_index = index_9[1]
    events5.loc[deuxieme_index, 'N°'] = 10

Index avec N°=9: [8, 9]

In [760]:
events5 = events5.rename(columns={'date': 'Type'})

In [761]:
events5['PAYS'] = events5['PAYS'].replace("Belgique", "Tunisie")

In [762]:
events5['PAYS'] = events5['PAYS'].replace("france", "Tunisie")

In [763]:
events5['Type'] = events5['Type'].replace("CLIENTS ETRANGERS", "CLIENTS TUNISIENS")

In [764]:
events5['departement'] = events5['departement'].str.strip()

In [765]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['HT', 'tva 19%', 'TTC', 'RECOUVREMENT', 'RESTANT']
for col in cols_to_convert:
    events5[col] = events5[col].apply(convert_comma_to_float)

In [766]:
events5 = events5.rename(columns={'HT': 'CA HT'})

In [767]:
events5['Banque'] = events5['Banque'].str.replace('€', 'TND')

In [768]:
import pandas as pd
events6 = pd.read_excel("new2023.xlsx",index_col=False,keep_default_na=True, sheet_name='Dépenses')

In [769]:
events6['DEPARTEMENT'] = events6['DEPARTEMENT'].replace("ELEC", "ELECTRICITE")
events6['DEPARTEMENT'] = events6['DEPARTEMENT'].replace("GCIVILE", "GENI CIVIL")

In [770]:
events6['DEPARTEMENT'] = events6['DEPARTEMENT'].str.strip()

In [771]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['TVA', 'TTC']
for col in cols_to_convert:
    events6[col] = events6[col].apply(convert_comma_to_float)

In [772]:
import pandas as pd
events7 = pd.read_excel("new2023.xlsx",index_col=False,keep_default_na=True, sheet_name='Salaires')

In [773]:
events7['DEPARTEMENT'] = events7['DEPARTEMENT'].replace("ELEC", "ELECTRICITE")
events7['DEPARTEMENT'] = events7['DEPARTEMENT'].replace("GCIVILE", "GENI CIVIL")

In [774]:
def convert_comma_to_float(value):
    try:
        if isinstance(value, str):
            value = value.replace(',', '.').replace(' ', '')
            return float(value)
        elif isinstance(value, (int, float)):
            return float(value)
        else:
            return None
    except ValueError:
        return None
cols_to_convert = ['CNSS', 'FISCAL', 'COUT TOTAL']
for col in cols_to_convert:
    events7[col] = events7[col].apply(convert_comma_to_float)

In [775]:
with pd.ExcelWriter("nettoye2022.xlsx") as writer:
    events.to_excel(writer, sheet_name="Export", index=False)
    events1.to_excel(writer, sheet_name="Local", index=False)
    events2.to_excel(writer, sheet_name="Dépenses", index=False)
    events3.to_excel(writer, sheet_name="Salaires", index=False)
events = pd.read_excel("nettoye2022.xlsx", sheet_name="Export")
events1 = pd.read_excel("nettoye2022.xlsx", sheet_name="Local")
events2 = pd.read_excel("nettoye2022.xlsx", sheet_name="Dépenses")
events3 = pd.read_excel("nettoye2022.xlsx", sheet_name="Salaires")

In [776]:
with pd.ExcelWriter("nettoye2023.xlsx") as writer:
    events4.to_excel(writer, sheet_name="Export", index=False)
    events5.to_excel(writer, sheet_name="Local", index=False)
    events6.to_excel(writer, sheet_name="Dépenses", index=False)
    events7.to_excel(writer, sheet_name="Salaires", index=False)
events4 = pd.read_excel("nettoye2023.xlsx", sheet_name="Export")
events5 = pd.read_excel("nettoye2023.xlsx", sheet_name="Local")
events6 = pd.read_excel("nettoye2023.xlsx", sheet_name="Dépenses")
events7 = pd.read_excel("nettoye2023.xlsx", sheet_name="Salaires")