In [2]:
import pandas as pd
data = pd.read_excel("DATA FORMATION BI 2022.xlsx",index_col=False,keep_default_na=True,sheet_name='EXPORT',header=4)

In [3]:
data.columns

Index(['N°', 'DATE', 'PAYS', 'Type', 'Nom du client', 'departement', 'CA €',
       'tx conv', 'CA TND', 'Recouvrement €', 'Restant €', 'Perte de change',
       'Banque'],
      dtype='object')

In [3]:
data.describe()

,N°,DATE,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change
count,29.000000,29,29.000000,2.900000e+01,29.000000,29.000000,29.000000,29.000000
mean,15.000000,2022-06-04 05:47:35.172413696,13150.852988,3.305900e+00,43475.404894,9226.904865,3923.948124,3057.311801
min,1.000000,2022-01-05 00:00:00,1071.794872,3.305900e+00,3543.246667,856.545091,0.000000,1208.606730
25%,8.000000,2022-03-28 00:00:00,3439.860000,3.305900e+00,11371.833170,2663.896215,267.774848,2141.651126
50%,15.000000,2022-05-21 00:00:00,9767.392500,3.305900e+00,32290.022870,7805.795972,1744.815283,3146.887160
75%,22.000000,2022-07-24 00:00:00,18500.750000,3.305900e+00,61161.629430,15116.171281,5482.483316,3888.132296
max,29.000000,2022-12-24 00:00:00,37657.293000,3.305900e+00,124491.244900,34060.970500,17301.999490,5207.368421
std,8.514693,NaN,10792.267757,1.355849e-15,35678.157977,7729.660598,5008.610155,1104.716845

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   N°               29 non-null     int64
 1   DATE             29 non-null     datetime64[ns]
 2   PAYS             29 non-null     object
 3   Type             29 non-null     object
 4   Nom du client    29 non-null     object
 5   departement      29 non-null     object
 6   CA €             29 non-null     float64
 7   tx conv          29 non-null     float64
 8   CA TND           29 non-null     float64
 9   Recouvrement €   29 non-null     float64
 10  Restant €        29 non-null     float64
 11  Perte de change  29 non-null     float64
 12  Banque           29 non-null     object
dtypes: datetime64[ns](1), float64(6), int64(1), object(5)
memory usage: 3.1+ KB

In [7]:
data.head()

,N°,DATE,PAYS,Type,Nom du client,departement,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change,Banque
0,1,2022-01-05,Belgique,CLIENTS ETRANGERS,BAQUILA,ELECTRICITE\n,5960.272394,3.3059,19704.06451,3221.768861,2738.503532,3231.517510,ATTIJARI TND
1,2,2022-01-10,France,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE\n,11809.074839,3.3059,39039.62051,9437.444929,2371.629911,5207.368421,BIAT TND
2,3,2022-02-15,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,30354.000000,3.3059,100347.28860,16407.567568,13946.432430,3209.143969,ATTIJARI TND
3,4,2022-02-26,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,FLUIDE,9767.392500,3.3059,32290.02287,7805.795972,1961.596528,3317.894737,BIAT TND
4,5,2022-02-26,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,8600.300000,3.3059,28431.73177,6873.091984,1727.208016,3521.052632,BIAT TND

In [8]:
data.head(10)

,N°,DATE,PAYS,Type,Nom du client,departement,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change,Banque
0,1,2022-01-05,Belgique,CLIENTS ETRANGERS,BAQUILA,ELECTRICITE\n,5960.272394,3.3059,19704.06451,3221.768861,2738.503532,3231.517510,ATTIJARI TND
1,2,2022-01-10,France,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE\n,11809.074839,3.3059,39039.62051,9437.444929,2371.629911,5207.368421,BIAT TND
2,3,2022-02-15,Belgique,CLIENTS ETRANGERS,BAQUILA,FLUIDE,30354.000000,3.3059,100347.28860,16407.567568,13946.432430,3209.143969,ATTIJARI TND
3,4,2022-02-26,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,FLUIDE,9767.392500,3.3059,32290.02287,7805.795972,1961.596528,3317.894737,BIAT TND
4,5,2022-02-26,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,8600.300000,3.3059,28431.73177,6873.091984,1727.208016,3521.052632,BIAT TND
5,6,2022-03-07,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,GENI CIVIL,29610.236000,3.3059,97888.47919,16005.532973,13604.703030,2109.922179,ATTIJARI TND
6,7,2022-03-28,Belgique,CLIENTS ETRANGERS,BAQUILA,GENI CIVIL,10118.000000,3.3059,33449.09620,5469.189189,4648.810811,3993.190661,ATTIJARI TND
7,8,2022-03-28,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,34060.970500,3.3059,112602.16240,34060.970500,0.000000,4845.263158,BIAT TND
8,9,2022-04-02,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,FLUIDE,14802.634000,3.3059,48936.02774,8001.423784,6801.210216,2171.206226,ATTIJARI TND
9,10,2022-04-02,france,CLIENTS ETRANGERS,DELTA BETA,FLUIDE,18500.750000,3.3059,61161.62943,18500.750000,0.000000,4774.736842,ZITOUNA €

In [9]:
data.tail()

,N°,DATE,PAYS,Type,Nom du client,departement,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change,Banque
24,25,2022-09-25,france,CLIENTS ETRANGERS,DELTA BETA,ELECTRICITE\n,13314.602339,3.3059,44016.743870,7832.119023,5482.483316,1530.096120,ZITOUNA TND
25,26,2022-10-24,France,CLIENTS ETRANGERS,TRIPARTIE TRAVAUX,GENI CIVIL,25697.491178,3.3059,84953.336090,15116.171281,10581.319900,1670.898805,ZITOUNA TND
26,27,2022-11-24,france,CLIENTS ETRANGERS,DELTA BETA,GENI CIVIL,27696.248811,3.3059,91561.028940,16291.911065,11404.337750,2141.651126,ZITOUNA TND
27,28,2022-12-03,Belgique,CLIENTS ETRANGERS,MAXIBIMAX,GENI CIVIL,2575.239480,3.3059,8513.484197,2058.051211,517.188269,3693.684211,BIAT TND
28,29,2022-12-24,France,CLIENTS ETRANGERS,K.WEST INGENIEURIE,GENI CIVIL,21911.745480,3.3059,72438.039380,12889.262047,9022.483433,2740.515761,ZITOUNA TND

In [1]:
import pandas as pd
data1 = pd.read_excel("DATA FORMATION BI 2022.xlsx",index_col=False,keep_default_na=True,sheet_name='LOCAL',header=4)

In [2]:
data1.columns

Index(['N°', 'Date', 'PAYS', 'date', 'NOM DU CLIENT', 'departement', 'CA HT',
       'tva 19%', 'TTC', 'RECOUVREMENT', 'RESTANT', 'Banque'],
      dtype='object')

In [3]:
data1.describe()

,N°,Date,CA HT,tva 19%,TTC,RECOUVREMENT,RESTANT
count,0.0,29,29.000000,29.000000,29.000000,29.000000,29.000000
mean,NaN,2022-04-27 16:33:06.206896640,52480.162557,9971.230886,62451.393442,50779.717413,11671.676030
min,NaN,2022-01-04 00:00:00,10251.376147,1947.761468,12199.137610,6437.539638,-17371.599620
25%,NaN,2022-02-14 00:00:00,28649.541284,5443.412844,34092.954130,23044.709641,0.000000
50%,NaN,2022-03-14 00:00:00,48619.723500,9237.747465,57857.470970,43058.192004,8043.884735
75%,NaN,2022-06-06 00:00:00,74974.311927,14245.119270,89219.431190,70090.206397,20625.015130
max,NaN,2022-12-12 00:00:00,108634.451073,20640.545700,129274.996800,129274.996777,42137.937160
std,NaN,NaN,30666.297602,5826.596545,36492.894146,34470.097736,14122.683873

In [4]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   N°             0 non-null      float64
 1   Date           29 non-null     datetime64[ns]
 2   PAYS           29 non-null     object
 3   date           29 non-null     object
 4   NOM DU CLIENT  27 non-null     object
 5   departement    29 non-null     object
 6   CA HT          29 non-null     float64
 7   tva 19%        29 non-null     float64
 8   TTC            29 non-null     float64
 9   RECOUVREMENT   29 non-null     float64
 10  RESTANT        29 non-null     float64
 11  Banque         29 non-null     object
dtypes: datetime64[ns](1), float64(6), object(5)
memory usage: 2.8+ KB

In [5]:
data1.head()

,N°,Date,PAYS,date,NOM DU CLIENT,departement,CA HT,tva 19%,TTC,RECOUVREMENT,RESTANT,Banque
0,NaN,2022-01-04,Tunisie,CLIENTS TUNISIENS,AB BUILDING,GENI CIVIL,58899.333107,11190.873290,70090.20640,70090.206397,0.00000,BIAT TND
1,NaN,2022-01-15,Tunisie,CLIENTS TUNISIENS,SPI DIAR JANNAH,FLUIDE,36183.354625,6874.837379,43058.19200,43058.192004,0.00000,ATTIJARI TND
2,NaN,2022-01-15,Tunisie,CLIENTS TUNISIENS,BEN MAHDOUD PALACE,GENI CIVIL,81843.860245,15550.333450,97394.19369,97394.193692,0.00000,BIAT TND
3,NaN,2022-01-23,Tunisie,CLIENTS TUNISIENS,AB BUILDING,FLUIDE,43842.664760,8330.106304,52172.77106,38387.735313,13785.03575,ZITOUNA TND
4,NaN,2022-01-24,Tunisie,CLIENTS TUNISIENS,AB BUILDING,ELECTRICITE\n,108634.451073,20640.545700,129274.99680,129274.996777,0.00000,ZITOUNA TND

In [6]:
import pandas as pd
data2 = pd.read_excel("DATA FORMATION BI 2022.xlsx",index_col=False,keep_default_na=True,sheet_name='DEPENSES',header=6)

In [7]:
data2.columns

Index(['N°', 'DATE', 'DEPARTEMENT', 'TYPE DE DEPENSES', 'FOURNISSEUR', 'HT',
       'TVA', 'TTC', 'REGLEMENT'],
      dtype='object')

In [8]:
data2.describe()

,N°,DATE,HT,TVA,TTC
count,137.000000,137,137.000000,137.000000,137.000000
mean,69.000000,2022-07-02 16:38:32.408759040,6552.034305,1244.886518,7796.920823
min,1.000000,2022-01-08 00:00:00,103.645000,19.692550,123.337550
25%,35.000000,2022-04-07 00:00:00,977.436810,185.712994,1163.149803
50%,69.000000,2022-06-30 00:00:00,1572.225038,298.722757,1870.947795
75%,103.000000,2022-09-19 00:00:00,2832.000000,538.080000,3370.080000
max,137.000000,2023-01-07 00:00:00,80325.000000,15261.750000,95586.750000
std,39.692569,NaN,14632.612778,2780.196428,17412.809206

In [9]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   N°                137 non-null    int64
 1   DATE              137 non-null    datetime64[ns]
 2   DEPARTEMENT       137 non-null    object
 3   TYPE DE DEPENSES  137 non-null    object
 4   FOURNISSEUR       137 non-null    object
 5   HT                137 non-null    float64
 6   TVA               137 non-null    float64
 7   TTC               137 non-null    float64
 8   REGLEMENT         137 non-null    object
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 9.8+ KB

In [10]:
import pandas as pd
data3 = pd.read_excel("DATA FORMATION BI 2022.xlsx",index_col=False,keep_default_na=True,sheet_name='SALAIRES',header=6)

In [11]:
data3.columns

Index(['SALARIE', 'MOIS', 'DEPARTEMENT', 'SALAIRE NET', 'CNSS', 'FISCAL',
       'TICKET RESTO', 'COUT TOTAL', 'banque'],
      dtype='object')

In [12]:
data3.describe()

       SALAIRE NET         CNSS       FISCAL  TICKET RESTO   COUT TOTAL
count   192.000000   192.000000   192.000000         192.0   192.000000
mean   3246.875000   630.147812   852.157812         200.0  4929.180625
std    1279.741722   252.748990   252.748990           0.0  1785.239702
min    1200.000000   225.890000   447.900000         200.0  2073.790000
25%    2450.000000   472.765000   694.775000         200.0  3817.540000
50%    3550.000000   690.015000   912.025000         200.0  5352.040000
75%    4237.500000   825.796250  1047.806250         200.0  6311.102500
max    5700.000000  1114.640000  1336.650000         200.0  8351.290000

In [13]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SALARIE       192 non-null    object
 1   MOIS          192 non-null    object
 2   DEPARTEMENT   192 non-null    object
 3   SALAIRE NET   192 non-null    int64
 4   CNSS          192 non-null    float64
 5   FISCAL        192 non-null    float64
 6   TICKET RESTO  192 non-null    int64
 7   COUT TOTAL    192 non-null    float64
 8   banque        192 non-null    object
dtypes: float64(3), int64(2), object(4)
memory usage: 13.6+ KB

In [14]:
import pandas as pd
dt = pd.read_excel("DATA FORMATION BI 2023.xlsx",index_col=False,keep_default_na=True,sheet_name='EXPORT',header=4)

In [15]:
dt.columns

Index(['N°', 'DATE', 'PAYS', 'Type', 'Nom du client', 'departement', 'N° FCT',
       'CA €', 'tx conv', 'CA TND', 'Recouvrement €', 'Restant €',
       'Perte de change', 'Banque'],
      dtype='object')

In [16]:
dt.describe()

,N°,N° FCT,CA €,tx conv,CA TND,Recouvrement €,Restant €,Perte de change
count,29.000000,29.000000,29.000000,2.900000e+01,29.000000,27.000000,29.000000,29.000000
mean,14.517241,18187.000000,14026.739655,3.370200e+00,47272.917986,12158.415556,2706.835517,3481.344828
std,8.209840,8.514693,12149.238147,2.259749e-15,40945.362402,10621.535145,7028.638106,788.420676
min,1.000000,18173.000000,1700.000000,3.370200e+00,5729.340000,1000.000000,0.000000,2000.000000
25%,8.000000,18180.000000,2926.000000,3.370200e+00,9861.205200,3030.500000,0.000000,3094.000000
50%,15.000000,18187.000000,10004.000000,3.370200e+00,33715.480800,9000.000000,0.000000,3442.000000
75%,21.000000,18194.000000,23963.480000,3.370200e+00,80761.720296,19664.390000,2339.630000,4072.000000
max,28.000000,18201.000000,35021.350000,3.370200e+00,118028.953770,33557.500000,35021.350000,4947.000000

In [17]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   N°               29 non-null     int64
 1   DATE             29 non-null     object
 2   PAYS             29 non-null     object
 3   Type             29 non-null     object
 4   Nom du client    29 non-null     object
 5   departement      29 non-null     object
 6   N° FCT           29 non-null     int64
 7   CA €             29 non-null     float64
 8   tx conv          29 non-null     float64
 9   CA TND           29 non-null     float64
 10  Recouvrement €   27 non-null     float64
 11  Restant €        29 non-null     float64
 12  Perte de change  29 non-null     int64
 13  Banque           29 non-null     object
dtypes: float64(5), int64(3), object(6)
memory usage: 3.3+ KB

In [18]:
import pandas as pd
dt1 = pd.read_excel("DATA FORMATION BI 2023.xlsx",index_col=False,keep_default_na=True,sheet_name='LOCAL',header=4)

In [19]:
dt1.columns

Index(['N°', 'Date', 'PAYS', 'date', 'NOM DU CLIENT', 'departement', 'N° FCT',
       'HT', 'tva 19%', 'TTC', 'RECOUVREMENT', 'RESTANT', 'Banque'],
      dtype='object')

In [21]:
dt1.describe()

,N°,Date,N° FCT,HT,tva 19%,TTC,RECOUVREMENT,RESTANT
count,29.000000,29,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000
mean,14.517241,2023-05-16 16:33:06.206896640,18217.000000,54447.827586,10362.073103,63875.179310,55287.153103,8588.026207
min,1.000000,2023-01-23 00:00:00,18203.000000,7593.000000,1442.670000,9035.670000,5052.290000,-9851.800000
25%,8.000000,2023-03-05 00:00:00,18210.000000,37407.000000,7107.330000,44514.330000,21621.660000,0.000000
50%,15.000000,2023-04-02 00:00:00,18217.000000,51808.000000,9851.800000,61263.580000,56365.400000,0.000000
75%,21.000000,2023-06-25 00:00:00,18224.000000,69830.000000,13267.700000,83097.700000,81949.350000,7600.000000
max,28.000000,2023-12-31 00:00:00,18231.000000,98943.000000,18799.170000,117742.170000,117742.170000,72754.440000
std,8.209840,NaN,8.514693,26801.639625,5089.726484,31353.088655,36203.719273,19421.802460

In [22]:
dt1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   N°             29 non-null     int64
 1   Date           29 non-null     datetime64[ns]
 2   PAYS           29 non-null     object
 3   date           29 non-null     object
 4   NOM DU CLIENT  27 non-null     object
 5   departement    29 non-null     object
 6   N° FCT         29 non-null     int64
 7   HT             29 non-null     int64
 8   tva 19%        29 non-null     float64
 9   TTC            29 non-null     float64
 10  RECOUVREMENT   29 non-null     float64
 11  RESTANT        29 non-null     float64
 12  Banque         29 non-null     object
dtypes: datetime64[ns](1), float64(4), int64(3), object(5)
memory usage: 3.1+ KB

In [23]:
import pandas as pd
dt2 = pd.read_excel("DATA FORMATION BI 2023.xlsx",index_col=False,keep_default_na=True,sheet_name='DEPENSES',header=6)

In [24]:
dt2.columns

Index(['N°', 'DATE', 'DEPARTEMENT', 'TYPE DE DEPENSES', 'FOURNISSEUR', 'HT',
       'TVA', 'TTC', 'REGLEMENT'],
      dtype='object')

In [25]:
dt2.describe()

,N°,DATE,HT,TVA,TTC
count,129.000000,129,129.000000,129.000000,129.000000
mean,65.000000,2023-07-03 16:11:09.767441920,7375.790698,1401.400233,8777.190930
min,1.000000,2023-01-02 00:00:00,500.000000,95.000000,595.000000
25%,33.000000,2023-04-21 00:00:00,1000.000000,190.000000,1190.000000
50%,65.000000,2023-06-30 00:00:00,1589.000000,301.910000,1890.910000
75%,97.000000,2023-09-30 00:00:00,3000.000000,570.000000,3570.000000
max,129.000000,2023-12-31 00:00:00,60000.000000,11400.000000,71400.000000
std,37.383151,NaN,15563.113327,2956.991532,18520.104859

In [26]:
dt2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129 entries, 0 to 128
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   N°                129 non-null    int64
 1   DATE              129 non-null    datetime64[ns]
 2   DEPARTEMENT       129 non-null    object
 3   TYPE DE DEPENSES  129 non-null    object
 4   FOURNISSEUR       129 non-null    object
 5   HT                129 non-null    int64
 6   TVA               129 non-null    float64
 7   TTC               129 non-null    float64
 8   REGLEMENT         129 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(2), object(4)
memory usage: 9.2+ KB

In [27]:
import pandas as pd
dt3 = pd.read_excel("DATA FORMATION BI 2023.xlsx",index_col=False,keep_default_na=True,sheet_name='SALAIRES',header=6)

In [28]:
dt3.columns

Index(['SALARIE', 'MOIS', 'DEPARTEMENT', 'SALAIRE NET', 'CNSS', 'FISCAL',
       'TICKET RESTO', 'COUT TOTAL', 'banque'],
      dtype='object')

In [30]:
dt3.describe()

       SALAIRE NET         CNSS       FISCAL  TICKET RESTO   COUT TOTAL
count   192.000000   192.000000   192.000000         192.0   192.000000
mean   3546.875000   700.507812  1015.847812         200.0  5463.230625
std    1279.741722   252.748990   252.748990           0.0  1785.239702
min    1500.000000   296.250000   611.590000         200.0  2607.840000
25%    2750.000000   543.125000   858.465000         200.0  4351.590000
50%    3850.000000   760.375000  1075.715000         200.0  5886.090000
75%    4537.500000   896.156250  1211.496250         200.0  6845.152500
max    6000.000000  1185.000000  1500.340000         200.0  8885.340000

In [31]:
dt3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192 entries, 0 to 191
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   SALARIE       192 non-null    object
 1   MOIS          192 non-null    object
 2   DEPARTEMENT   192 non-null    object
 3   SALAIRE NET   192 non-null    int64
 4   CNSS          192 non-null    float64
 5   FISCAL        192 non-null    float64
 6   TICKET RESTO  192 non-null    int64
 7   COUT TOTAL    192 non-null    float64
 8   banque        192 non-null    object
dtypes: float64(3), int64(2), object(4)
memory usage: 13.6+ KB